### ISSUE TITLE
does this work for 1.16.5 fabric?

### ISSUE THREAD

**Issue by Skidddd22** [AriliusClient/CTEC#2]
as in, can i put this in 1.16.5 fabric mods folder with it still working?
im a skid pls help

**Comment by constantinDev** [comment]
It does, although you have to build it yourself for it to work and ignore the version change. It works with 1.16.5, although its not stable on it, so i made it only work on 1.16.4 in the prebuild. To make it work on 1.16.5, either:

1. Open the jarfile with 7zip and edit the fabric.mod.json file to say `"minecraft": ">=1.16.4"` instead of `"minecraft": "1.16.4"` or
2. Replace the line in the source code and build it yourself

**Comment by Skidddd22** [comment]
thank you for the tutorial i am skid so i know nothing about html the language in which minecraft is written

**Comment by Skidddd22** [comment]
(i am unironically a skid)

**Comment by constantinDev** [comment]
this gotta be satire lol

**Comment by Skidddd22** [comment]
skid coding
